### ISSUE TITLE
Interface window is too tall for some widescreen laptop monitiors

### ISSUE THREAD

**Issue by Da-Boom** [Rikerz/VRC#6] opened 2015-01-04 09:56 UTC
I am running a laptop that has a monitor of 1366*768 resolution and i cant use the corrupter in its current (or current beta) configuration because the buttons at the bottom keep getting cut off, and auto-hiding the task bar does not work, because the window is too long.

This could maybe be fixed by repositioning the buttons to the right, or making the window resizable (to a point)

**Comment by Rikerz** [comment] 2015-01-05 07:55
Hi Da-Boom, I realize that I haven't touched this in a while, but I will be looking at incorporating some of the pull requests and improvements in the near future. However, I will also be looking to possibly re-write the program so it can be used on Windows, Linux, and Mac OS X. As I am no longer a student, I have lost access to Visual Studio, which I was using to work on this. In hindsight, I probably should have started with something open source, but the GUI development was just too easy in Visual Studio.

In the meantime you could try the fork http://github.com/link2x/VRC_Tabbed which has tabbed out the interface. As I cannot adequately compile and test pull requests, I will not be merging them into this repository. It looks like the fork has a compiled version you can use.

Keep and eye out for a new version here in a while which should support Windows, Mac OS X, and Linux.

**Comment by Davipb** [comment] 2015-01-12 21:23
@Da-Boom While they don't fix it, you could try using [Alt-Drag](https://stefansundin.github.io/altdrag/), which allows you do drag windows outside of the normal boundaries.  
  
@Rikerz Can't you just use [Visual Studio Express](http://www.visualstudio.com/downloads/download-visual-studio-vs)? It's the free version of VS that has the GUI editor and everything. I just forked the repository and confirmed that it works fine in VS Express.

**Comment by Rikerz** [comment] 2015-01-13 00:33
@Davipb You are right about Visual Studio, I had been out of the loop for a bit. I'll look at getting this an a few other fixes in soon.

**Comment by Rikerz** [comment] 2015-01-16 03:16
@Da-Boom The new version should resolve this issue, so I will close it. If it does not, feel free to open another issue.

**Closed by Rikerz** 2015-01-16 03:16 UTC
